
Vagrant.require_version ">= 1.6.2"

Vagrant.configure(2) do |config|

  config.vm.box = "cliente"
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "MultichainCliente"
  config.vm.network :private_network, :ip => '10.4.4.5'

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.name = "cliente"
  end

  config.vm.provision "shell", :inline => "wget http://www.multichain.com/download/multichain-1.0-beta-2.tar.gz"
  config.vm.provision "shell", :inline => "tar -xvzf multichain-1.0-beta-2.tar.gz"
  config.vm.provision "shell", :inline => "cd multichain-1.0-beta-2 && mv multichaind multichain-cli multichain-util /usr/local/bin"
