
Vagrant.require_version ">= 1.6.2"

Vagrant.configure(2) do |config|

  config.vm.box = "servidor"
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "MultichainServidor"
  config.vm.network :private_network, :ip => '10.4.4.4'
